services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    user: "1027:100"
    volumes:
      - /volume1/docker/flower/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

  flower:
    image: mher/flower
    command: celery flower
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    volumes:
      - /volume1/docker/flower:/data
    depends_on:
      - rabbitmq
    user: "1027:100"

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_MODEL: ${OPENAI_MODEL}

  worker:
    build: .
    command: celery -A async_tasks worker --loglevel=info
    depends_on:
      - backend
      - rabbitmq
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_MODEL: ${OPENAI_MODEL}
