services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: nas
        target: /etc/nginx/nginx.conf
        read_only: true
        volume:
          subpath: configs/nginx.conf
      - type: volume
        source: nas
        target: /etc/nginx/certs
        read_only: true
        volume:
          subpath: certs/apps.ethanturk.com

volumes:
  nas:
    external: true
